name: certval-services

services:
  certval.apiservice:
    image: ${DOCKER_REGISTRY}certvalapiservice
    build:
      context: ../
      dockerfile: CertVal.ApiService/Dockerfile
    ports:
      - "${APISERVICE_HTTP_PORT}:8080"
    restart: unless-stopped
    networks:
      - certval-net

  certval.emailservice:
    image: ${DOCKER_REGISTRY}certvalemailservice
    build:
      context: ../
      dockerfile: CertVal.EmailService/Dockerfile
    restart: unless-stopped
    networks:
      - certval-net

  certval.web:
    image: ${DOCKER_REGISTRY}certvalweb
    build:
      context: ../
      dockerfile: CertVal.Web/Dockerfile
    ports:
      - "${WEB_HTTP_PORT}:3000"
    depends_on:
      certval.apiservice:
        condition: service_started
    restart: unless-stopped
    networks:
      - certval-net

networks:
  certval-net:
    name: certval-net
    external: true
