// <auto-generated />
using System;
using System.Collections.Generic;
using CertVal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CertVal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618122403_AddMonitoredEndpoints")]
    partial class AddMonitoredEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CertVal.Core.Entities.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastUsedIpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_ApiTokens_ExpiresAt")
                        .HasFilter("\"ExpiresAt\" IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ApiTokens_UserId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_ApiTokens_User_Active");

                    b.HasIndex("UserId", "IsActive", "ExpiresAt")
                        .HasDatabaseName("IX_ApiTokens_User_Active_Expires");

                    b.ToTable("ApiTokens", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FileFormat")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBundle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OcspLastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OcspLastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OcspResponderUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OcspRevocationReason")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("OcspRevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OcspStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("ParentCertificateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PreviousCertificateId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotAfter")
                        .HasDatabaseName("IX_Certificates_NotAfter");

                    b.HasIndex("ParentCertificateId")
                        .HasDatabaseName("IX_Certificates_ParentId")
                        .HasFilter("\"ParentCertificateId\" IS NOT NULL");

                    b.HasIndex("PreviousCertificateId");

                    b.HasIndex("Thumbprint")
                        .HasDatabaseName("IX_Certificates_Thumbprint");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_Certificates_WorkspaceId");

                    b.HasIndex("OcspLastCheckedAt", "OcspStatus")
                        .HasDatabaseName("IX_Certificates_OcspLastCheckedAt");

                    b.HasIndex("Subject", "Issuer")
                        .HasDatabaseName("IX_Certificates_Subject_Issuer");

                    b.HasIndex("WorkspaceId", "IsBundle")
                        .HasDatabaseName("IX_Certificates_Workspace_Bundle");

                    b.HasIndex("WorkspaceId", "NotAfter")
                        .HasDatabaseName("IX_Certificates_Workspace_Expiry");

                    b.HasIndex("WorkspaceId", "Status")
                        .HasDatabaseName("IX_Certificates_Workspace_Status");

                    b.HasIndex("WorkspaceId", "Issuer", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Certificates_Workspace_Issuer_Serial")
                        .HasFilter("\"SerialNumber\" IS NOT NULL AND \"IsBundle\" = false");

                    b.HasIndex("WorkspaceId", "NotAfter", "Status")
                        .HasDatabaseName("IX_Certificates_Workspace_Expiry_Status");

                    b.ToTable("Certificates", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CheckIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(360);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastGrade")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("LastProtocol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("LastReachable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LeafNotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeafSubject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LeafThumbprint")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Port")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(443);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_MonitoredEndpoints_WorkspaceId");

                    b.HasIndex("IsEnabled", "LastCheckedAt")
                        .HasDatabaseName("IX_MonitoredEndpoints_Due");

                    b.HasIndex("WorkspaceId", "Host", "Port")
                        .IsUnique()
                        .HasDatabaseName("IX_MonitoredEndpoints_Workspace_Host_Port");

                    b.ToTable("MonitoredEndpoints", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.NotificationHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResponseData")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId")
                        .HasDatabaseName("IX_NotificationHistory_CertificateId");

                    b.HasIndex("NotificationRuleId")
                        .HasDatabaseName("IX_NotificationHistory_RuleId");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("IX_NotificationHistory_ScheduledAt");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("IX_NotificationHistory_Status_Scheduled");

                    b.HasIndex("Status", "ScheduledAt", "RetryCount")
                        .HasDatabaseName("IX_NotificationHistory_Processing");

                    b.ToTable("NotificationHistory", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.NotificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChannelConfig")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasDefaultValue("{}");

                    b.Property<int>("ChannelType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysBeforeExpiry")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RecipientAggregationMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_NotificationRules_WorkspaceId");

                    b.HasIndex("WorkspaceId", "IsEnabled")
                        .HasDatabaseName("IX_NotificationRules_Workspace_Enabled");

                    b.ToTable("NotificationRules", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.StoredEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<Guid?>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_StoredEvents_CorrelationId")
                        .HasFilter("\"CorrelationId\" IS NOT NULL");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_StoredEvents_EventId");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_StoredEvents_EventType");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("IX_StoredEvents_Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_StoredEvents_OccurredAt");

                    b.HasIndex("StoredAt")
                        .HasDatabaseName("IX_StoredEvents_StoredAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_StoredEvents_UserId")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.HasIndex("AggregateType", "AggregateId")
                        .HasDatabaseName("IX_StoredEvents_Aggregate");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_StoredEvents_Type_OccurredAt");

                    b.HasIndex("UserId", "OccurredAt")
                        .HasDatabaseName("IX_StoredEvents_User_OccurredAt")
                        .HasFilter("\"UserId\" IS NOT NULL");

                    b.HasIndex("WorkspaceId", "OccurredAt")
                        .HasDatabaseName("IX_StoredEvents_Workspace_OccurredAt")
                        .HasFilter("\"WorkspaceId\" IS NOT NULL");

                    b.HasIndex("AggregateType", "AggregateId", "OccurredAt")
                        .HasDatabaseName("IX_StoredEvents_Aggregate_OccurredAt");

                    b.ToTable("StoredEvents", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("en");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("UTC");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("EmailConfirmationToken")
                        .HasDatabaseName("IX_Users_EmailConfirmationToken")
                        .HasFilter("\"EmailConfirmationToken\" IS NOT NULL");

                    b.HasIndex("PasswordResetToken")
                        .HasDatabaseName("IX_Users_PasswordResetToken")
                        .HasFilter("\"PasswordResetToken\" IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Users_Status");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowMemberInvites")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("AutoDeleteExpiredCertificates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxCertificates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("OcspMonitoringEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsPublic")
                        .HasDatabaseName("IX_Workspaces_IsPublic");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("IX_Workspaces_OwnerId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Workspaces_Owner_Name");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvitationToken")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("InvitationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InvitationToken")
                        .HasDatabaseName("IX_WorkspaceMembers_InvitationToken")
                        .HasFilter("\"InvitationToken\" IS NOT NULL");

                    b.HasIndex("InvitedByUserId")
                        .HasDatabaseName("IX_WorkspaceMembers_InvitedBy")
                        .HasFilter("\"InvitedByUserId\" IS NOT NULL");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_WorkspaceMembers_UserId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("IX_WorkspaceMembers_WorkspaceId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkspaceMembers_Workspace_User");

                    b.ToTable("WorkspaceMembers", (string)null);
                });

            modelBuilder.Entity("CertVal.Core.Entities.ApiToken", b =>
                {
                    b.HasOne("CertVal.Core.Entities.User", "User")
                        .WithMany("ApiTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CertVal.Core.Entities.Certificate", b =>
                {
                    b.HasOne("CertVal.Core.Entities.Certificate", "ParentCertificate")
                        .WithMany("ChildCertificates")
                        .HasForeignKey("ParentCertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertVal.Core.Entities.Certificate", "PreviousCertificate")
                        .WithMany()
                        .HasForeignKey("PreviousCertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CertVal.Core.Entities.Workspace", "Workspace")
                        .WithMany("Certificates")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCertificate");

                    b.Navigation("PreviousCertificate");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CertVal.Core.Entities.MonitoredEndpoint", b =>
                {
                    b.HasOne("CertVal.Core.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CertVal.Core.Entities.NotificationHistory", b =>
                {
                    b.HasOne("CertVal.Core.Entities.Certificate", "Certificate")
                        .WithMany("NotificationHistory")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertVal.Core.Entities.NotificationRule", "NotificationRule")
                        .WithMany("NotificationHistory")
                        .HasForeignKey("NotificationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Certificate");

                    b.Navigation("NotificationRule");
                });

            modelBuilder.Entity("CertVal.Core.Entities.NotificationRule", b =>
                {
                    b.HasOne("CertVal.Core.Entities.Workspace", "Workspace")
                        .WithMany("NotificationRules")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CertVal.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("CertVal.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CertVal.Core.Entities.Workspace", b =>
                {
                    b.HasOne("CertVal.Core.Entities.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("CertVal.Core.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("CertVal.Core.Entities.User", "InvitedByUser")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CertVal.Core.Entities.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CertVal.Core.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("CertVal.Core.Entities.Certificate", b =>
                {
                    b.Navigation("ChildCertificates");

                    b.Navigation("NotificationHistory");
                });

            modelBuilder.Entity("CertVal.Core.Entities.NotificationRule", b =>
                {
                    b.Navigation("NotificationHistory");
                });

            modelBuilder.Entity("CertVal.Core.Entities.User", b =>
                {
                    b.Navigation("ApiTokens");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("CertVal.Core.Entities.Workspace", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Members");

                    b.Navigation("NotificationRules");
                });
#pragma warning restore 612, 618
        }
    }
}
